# Site Settings
title: Lei Yang
email: lei.yang.cs.art@gmail.com
description: Drink 23 cups of water a day. Keep running is tired, but makes good shape. A Java Programmer, Blog writer and App learner.
baseurl: ""
url: "http://www.leiyangblog.com"
twitter_username:
github_username: Ray-Young

markdown: kramdown
permalink: pretty
excerpt_separator: "<!--MORE-->"

kramdown:
    input: GFM

gems:
  - jekyll-feed
