# Site Settings
title: 风趣的执念
email: ray.yang30@gmail.com
description: For interesting ideas and interesting people
baseurl: ""
url: "http://www.leiyangblog.com"
twitter_username:
github_username: Ray-Young

markdown: kramdown
permalink: pretty
excerpt_separator: "<!--MORE-->"

kramdown:
    input: GFM
