# Site Settings
title: Lei(Raymond) Yang
email: ray.yang30@gmail.com
description: To be the Better Me.
baseurl: ""
url: "http://www.leiyangblog.com"
twitter_username:
github_username: Ray-Young

markdown: kramdown
permalink: pretty
excerpt_separator: "<!--MORE-->"

kramdown:
    input: GFM
