# Site settings
title: Lei Yang
description: "Keep running is tired, but keeps good shape! A Java Programmer"
url: "http://www.leiyangblog.com"
author:
  name: "Lei Yang"
  email: "lei.yang.cs.art@gmail.com"
  url: "http://www.leiyangblog.com"

# Social icons
github_username: Ray-Young
facebook_username: andy.yang.96199
linkedin_username: lei-yang-293231115
email: lei.yang.cs.art@gmail.com

# Build settings
baseurl:  # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

