# Site settings
title: Raymond Yang
description: "Java Programmer. Open to learn any techniques to make things work. Strive to be a full-stack developer."
url: "http://www.leiyangblog.com"
author:
  name: "Raymond Yang"
  url: "http://www.leiyangblog.com"

# Social icons
github_username: Ray-Young
linkedin_username: raymond-yang-293231115/

# Build settings
baseurl:  # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins:
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# Gems
plugins: [jekyll-paginate]

